"""
    VulkanShaders

Compiles GLSL 450 source code to SPIR-V bytecode using `glslang_jll`
and creates Vulkan shader modules.

Also provides functions to generate Vulkan-compatible GLSL 450 fragment
shaders from `TextureSpec` arrays (replacing the OpenGL 330 shaders
generated by `CustomFragShad.jl`).
"""
module VulkanShaders

using Vulkan
using VulkanCore
using glslang_jll
using Logging

export compile_glsl_to_spirv, create_shader_module
export generate_vulkan_vertex_shader, generate_vulkan_zerovbo_vertex_shader
export generate_vulkan_fragment_shader
export generate_vulkan_text_fragment_shader

# ─── GLSL → SPIR-V compilation ─────────────────────────────────────────

"""
    compile_glsl_to_spirv(stage::Symbol, glsl_source::String) → Vector{UInt8}

Writes GLSL source to a temporary file, invokes `glslangValidator` to
compile it to SPIR-V, and reads back the binary.

`stage` must be one of `:vert`, `:frag`, `:comp`.
"""
function compile_glsl_to_spirv(stage::Symbol, glsl_source::String)::Vector{UInt8}
    ext = Dict(:vert => ".vert", :frag => ".frag", :comp => ".comp")
    haskey(ext, stage) || error("Unknown shader stage: $stage")

    src_path = tempname() * ext[stage]
    spv_path = tempname() * ".spv"

    try
        write(src_path, glsl_source)

        validator = glslang_jll.glslangValidator_path
        output = IOBuffer()
        cmd = `$validator -V --target-env vulkan1.2 -o $spv_path $src_path`
        proc = run(pipeline(cmd; stdout=output, stderr=output); wait=true)
        if !success(proc)
            out_str = String(take!(output))
            error("glslangValidator failed for $stage shader:\n$out_str")
        end

        return read(spv_path)
    catch e
        # Log the GLSL source for debugging
        @error "Shader compilation failed" stage exception=(e, catch_backtrace())
        for (i, line) in enumerate(split(glsl_source, '\n'))
            @error "  $i: $line"
        end
        rethrow(e)
    finally
        rm(src_path; force=true)
        rm(spv_path; force=true)
    end
end

"""
    create_shader_module(device, spirv_bytes) → ShaderModule

Creates a Vulkan ShaderModule from pre-compiled SPIR-V bytes.
"""
function create_shader_module(device::Device, spirv_bytes::Vector{UInt8})::ShaderModule
    @assert length(spirv_bytes) % 4 == 0 "SPIR-V byte count must be a multiple of 4"
    code = collect(reinterpret(UInt32, spirv_bytes))
    sm_ref = Ref(VulkanCore.VkShaderModule(C_NULL))
    GC.@preserve code begin
        smci = Ref(VulkanCore.VkShaderModuleCreateInfo(
            VulkanCore.VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
            C_NULL, UInt32(0),
            UInt32(length(code) * 4),
            pointer(code)
        ))
        fptr = Vulkan.function_pointer(Vulkan.global_dispatcher[], device, :vkCreateShaderModule)
        res = ccall(fptr, VulkanCore.VkResult,
            (VulkanCore.VkDevice, Ptr{VulkanCore.VkShaderModuleCreateInfo}, Ptr{Cvoid}, Ptr{VulkanCore.VkShaderModule}),
            device.vks, smci, C_NULL, sm_ref)
        res != VulkanCore.VK_SUCCESS && error("vkCreateShaderModule failed: $res")
    end
    return ShaderModule(sm_ref[], device, Threads.Atomic{UInt64}(1))
end

# ─── Vulkan GLSL 450 vertex shader ─────────────────────────────────────

"""
    generate_vulkan_vertex_shader() → String

Returns a GLSL 450 vertex shader compatible with the quad geometry format
used by MedEye3d (position vec3, color vec3, texcoord vec2; stride = 8 floats).

Push constants provide per-panel zoom/pan (uvScale, uvOffset).
"""
function generate_vulkan_vertex_shader()::String
    return """
    #version 450

    layout(location = 0) in vec3 aPos;
    layout(location = 1) in vec3 aColor;
    layout(location = 2) in vec2 aTexCoord;

    layout(location = 0) out vec3 ourColor;
    layout(location = 1) out vec2 TexCoord0;

    layout(push_constant) uniform PushConstants {
        vec2 uvScale;
        vec2 uvOffset;
        vec2 ndcMin;   // unused by VBO shader, but must match layout
        vec2 ndcMax;
    } pc;

    void main() {
        gl_Position = vec4(aPos, 1.0);
        ourColor = aColor;
        // Apply zoom/pan: center at 0.5, scale by 1/zoom, offset by pan
        TexCoord0 = (aTexCoord - 0.5) * pc.uvScale + 0.5 + pc.uvOffset;
    }
    """
end

"""
    generate_vulkan_zerovbo_vertex_shader() → String

Generates a procedural full-screen quad vertex shader using `gl_VertexIndex`.
Eliminates vertex/index buffer creation, memory allocation, and bindings.
"""
function generate_vulkan_zerovbo_vertex_shader()::String
    return """
    #version 450

    layout(location = 0) out vec3 ourColor;
    layout(location = 1) out vec2 TexCoord0;

    layout(push_constant) uniform PushConstants {
        vec2 uvScale;
        vec2 uvOffset;
        vec2 ndcMin;   // (left, bottom) in NDC
        vec2 ndcMax;   // (right, top) in NDC
    } pc;

    void main() {
        // 6 vertices for 2 triangles forming a quad
        // Use NDC bounds from push constants instead of hardcoded [-1,1]
        vec2 positions[6] = vec2[](
            vec2(pc.ndcMin.x, pc.ndcMin.y), vec2(pc.ndcMax.x, pc.ndcMin.y), vec2(pc.ndcMin.x, pc.ndcMax.y),
            vec2(pc.ndcMin.x, pc.ndcMax.y), vec2(pc.ndcMax.x, pc.ndcMin.y), vec2(pc.ndcMax.x, pc.ndcMax.y)
        );
        // OpenGL-compatible UV mapping for use with negative-height viewport.
        // The negative viewport flips NDC Y (Y-up like OpenGL), but Vulkan's
        // texture V=0 is at the TOP of the image (opposite to OpenGL's V=0 at bottom).
        // To compensate, we map V=0 to the bottom vertex and V=1 to the top vertex,
        // which inverts the texture vertically to match OpenGL's display convention.
        vec2 texCoords[6] = vec2[](
            vec2(0.0, 0.0), vec2(1.0, 0.0), vec2(0.0, 1.0),
            vec2(0.0, 1.0), vec2(1.0, 0.0), vec2(1.0, 1.0)
        );
        gl_Position = vec4(positions[gl_VertexIndex], 0.0, 1.0);
        ourColor = vec3(1.0);
        TexCoord0 = (texCoords[gl_VertexIndex] - 0.5) * pc.uvScale + 0.5 + pc.uvOffset;
    }
    """
end

# ─── Vulkan GLSL 450 text fragment shader ──────────────────────────────

"""
    generate_vulkan_text_fragment_shader() → String

Simple text-rendering fragment shader for Vulkan (equivalent to
`ShadersAndVerticiesForText.createFragmentShader`).
"""
function generate_vulkan_text_fragment_shader()::String
    return """
    #version 450

    layout(location = 0) in vec3 ourColor;
    layout(location = 1) in vec2 TexCoord0;

    layout(location = 0) out vec4 FragColor;

    layout(set = 0, binding = 0) uniform usampler2D TextTexture1;

    void main() {
        uint text1Texel = texture(TextTexture1, TexCoord0).r;
        if (text1Texel > 0u) {
            FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        } else {
            FragColor = vec4(1.0, 1.0, 1.0, 1.0);
        }
    }
    """
end

# ─── Vulkan GLSL 450 fragment shader generator ─────────────────────────

# Re-use the shader generation logic from CustomFragShad but target GLSL 450.
# The key differences from GLSL 330:
#   1. `#version 450` instead of `#version 330`
#   2. `layout(set=0, binding=N)` for samplers instead of `uniform sampler2D name`
#   3. `layout(location=0) in/out` for inputs/outputs
#   4. Uniform parameters go into a UBO at set=1

"""
    generate_vulkan_fragment_shader(texture_specs, color) → String

Generates a Vulkan GLSL 450 fragment shader that composites all texture
layers (main image, PET overlay, continuous masks, discrete masks, bone
surfaces) exactly like the OpenGL version in `CustomFragShad.jl`.

Each texture gets `layout(set=0, binding=N)` for its sampler.
Per-texture parameters (visibility, min/max, colors, etc.) are passed
via a UBO at `layout(set=1, binding=0)`.
"""
function generate_vulkan_fragment_shader(texture_specs, color)::String
    n_tex = length(texture_specs)

    # Build sampler declarations (isampler2D for integer textures, sampler2D for float)
    sampler_decls = join(map(enumerate(texture_specs)) do (i, spec)
        binding = i - 1
        sampler_type = spec.isIntegerTexture ? "isampler2D" : "sampler2D"
        "layout(set = 0, binding = $binding) uniform $sampler_type $(spec.name);"
    end, "\n    ")

    # Build UBO struct for per-texture parameters
    ubo_members = join(map(enumerate(texture_specs)) do (i, spec)
        n = spec.name
        """
        int   $(n)isVisible;
        float $(n)minValue;
        float $(n)maxValue;
        float $(n)ValueRange;
        float $(n)maskContribution;
        vec4  $(n)ColorMask;
        int   $(n)allowedIDCount;
        float $(n)allowedIDs[16];
        """
    end, "\n        ")

    # Build texture reads (integer textures read as int, then convert to float)
    tex_reads = join(map(texture_specs) do spec
        if spec.isIntegerTexture
            "int $(spec.name)Res_i = texture($(spec.name), coord).r;\n        float $(spec.name)Res = float($(spec.name)Res_i);"
        else
            "float $(spec.name)Res = texture($(spec.name), coord).r;"
        end
    end, "\n        ")

    # Classify textures
    texturesNotCont = filter(t -> !t.isContinuusMask && !t.isMultiDiscreteMask, texture_specs)
    texturesCont = filter(t -> t.isContinuusMask, texture_specs)
    texturesDiscrete = filter(t -> t.isMultiDiscreteMask, texture_specs)

    # Main image color computation
    mainR = _main_color_expr(texturesNotCont, "r")
    mainG = _main_color_expr(texturesNotCont, "g")
    mainB = _main_color_expr(texturesNotCont, "b")

    isVisibleList = join(map(t -> t.isMainImage ? "params.$(t.name)isVisible" : "0", texture_specs), " + ")
    if isempty(isVisibleList); isVisibleList = "1.0"; end

    # Mask overlay code (same layering as OpenGL version)
    mask_code = _generate_mask_overlay_code(texturesNotCont, texturesCont, texturesDiscrete)

    # Multi-color table functions
    cont_funcs = _generate_multicolor_funcs(texturesCont)
    discrete_funcs = _generate_discrete_color_funcs(texturesDiscrete)

    return """
    #version 450

    layout(location = 0) in vec3 ourColor;
    layout(location = 1) in vec2 TexCoord0;
    layout(location = 0) out vec4 FragColor;

    // Texture samplers
    $sampler_decls

    // Per-texture parameters UBO
    layout(set = 1, binding = 0) uniform TextureParams {
        $ubo_members
    } params;

    float changeClip(float minVal, float maxVal, float value, float color, float range) {
        if (value < minVal) {
            return 0.0;
        } else if (value >= maxVal) {
            return color;
        } else {
            return color * ((value - minVal) / max(range, 0.001));
        }
    }

    $cont_funcs
    $discrete_funcs

    vec3 getPixelColor(vec2 coord) {
        $tex_reads

        float todiv = max(float($isVisibleList), 1.0);

        vec3 baseColor = vec3(
            ($mainR) / todiv,
            ($mainG) / todiv,
            ($mainB) / todiv
        );

        $mask_code

        return baseColor;
    }

    void main() {
        FragColor = vec4(getPixelColor(TexCoord0), 1.0);
    }
    """
end

# ─── Internal helpers for shader generation ─────────────────────────────

function _main_color_expr(textures_not_cont, channel)
    parts = String[]
    for t in textures_not_cont
        if t.isMainImage
            push!(parts, "changeClip(params.$(t.name)minValue, params.$(t.name)maxValue, $(t.name)Res, params.$(t.name)ColorMask.$channel, params.$(t.name)ValueRange) * float(params.$(t.name)isVisible)")
        end
    end
    return isempty(parts) ? "0.0" : join(parts, " + ")
end

function _generate_mask_overlay_code(notcont, cont, discrete)
    code = ""

    # 1. Nuclear/PET overlay
    for x in notcont
        if !x.isMainImage && x.isNuclearMask
            n = x.name
            code *= """
                if (params.$(n)isVisible == 1) {
                    vec3 petOnly_$(n) = vec3(0.0);
                    if (params.$(n)minValue == params.$(n)maxValue) {
                        if (abs($(n)Res - params.$(n)minValue) < 0.1) {
                            petOnly_$(n) = vec3(params.$(n)ColorMask.r, params.$(n)ColorMask.g, params.$(n)ColorMask.b);
                        }
                    } else if ($(n)Res > params.$(n)minValue) {
                        float normalizedVal_$(n) = clamp(($(n)Res - params.$(n)minValue) / max(params.$(n)ValueRange, 0.001), 0.0, 1.0);
                        if (normalizedVal_$(n) > 0.0) {
                            float intensity_$(n) = pow(normalizedVal_$(n), 0.4);
                            vec3 maskColor_$(n) = vec3(
                                changeClip(params.$(n)minValue, params.$(n)maxValue, $(n)Res, params.$(n)ColorMask.r, params.$(n)ValueRange),
                                changeClip(params.$(n)minValue, params.$(n)maxValue, $(n)Res, params.$(n)ColorMask.g, params.$(n)ValueRange),
                                changeClip(params.$(n)minValue, params.$(n)maxValue, $(n)Res, params.$(n)ColorMask.b, params.$(n)ValueRange)
                            );
                            petOnly_$(n) = clamp(maskColor_$(n) * intensity_$(n) * 1.8, 0.0, 1.0);
                        }
                    }
                    float blend_$(n) = params.$(n)maskContribution;
                    float ctW_$(n) = clamp(2.0 * (1.0 - blend_$(n)), 0.0, 1.0);
                    float petW_$(n) = clamp(2.0 * blend_$(n), 0.0, 1.0);
                    baseColor = clamp(baseColor * ctW_$(n) + petOnly_$(n) * petW_$(n), 0.0, 1.0);
                }
            """
        end
    end

    # 2. Continuous multi-color maps
    for x in cont
        if !x.isMainImage
            n = x.name
            code *= """
                if (params.$(n)isVisible == 1 && abs($(n)Res) > 0.00001) {
                    float alpha = params.$(n)maskContribution;
                    alpha = clamp(alpha * 2.0, 0.5, 1.0);
                    vec3 maskColor = getMultiColor_$(n)($(n)Res);
                    if (maskColor != vec3(0.0)) {
                        baseColor = mix(baseColor, maskColor, alpha);
                    }
                }
            """
        end
    end

    # 3. Discrete segmentation masks
    for x in discrete
        if !x.isMainImage
            n = x.name
            code *= """
                if (params.$(n)isVisible == 1 && abs($(n)Res) > 0.00001) {
                    bool showThis_$(n) = false;
                    if (params.$(n)allowedIDCount > 0) {
                        for (int _aidx = 0; _aidx < 16; _aidx++) {
                            if (_aidx >= params.$(n)allowedIDCount) { break; }
                            if (abs($(n)Res - params.$(n)allowedIDs[_aidx]) < 0.1) {
                                showThis_$(n) = true;
                                break;
                            }
                        }
                    } else {
                        showThis_$(n) = (params.$(n)minValue < params.$(n)maxValue) || (abs($(n)Res - params.$(n)minValue) < 0.1);
                    }
                    if (showThis_$(n)) {
                        float alpha = clamp(params.$(n)maskContribution, 0.0, 1.0);
                        vec3 maskColor = getDiscreteColor_$(n)($(n)Res);
                        if (maskColor != vec3(0.0)) {
                            baseColor = mix(baseColor, maskColor, alpha);
                        }
                    }
                }
            """
        end
    end

    # 4. Top layer: bone overlay / label overlays
    for x in notcont
        if !x.isMainImage && !x.isNuclearMask
            n = x.name
            if occursin("Bone_Overlay", n)
                # Combined bone mask: surface=1 (cyan), marrow=2 (yellow), both=3 (green)
                code *= """
                if (params.$(n)isVisible == 1 && abs($(n)Res) > 0.1) {
                    float labelAlpha_$(n) = clamp(params.$(n)maskContribution, 0.0, 1.0);
                    vec3 boneColor_$(n);
                    int boneVal_$(n) = $(n)Res_i;
                    if (boneVal_$(n) == 1) {
                        boneColor_$(n) = vec3(0.0, 1.0, 1.0);  // Surface: cyan
                    } else if (boneVal_$(n) == 2) {
                        boneColor_$(n) = vec3(1.0, 1.0, 0.0);  // Marrow: yellow
                    } else if (boneVal_$(n) == 3) {
                        boneColor_$(n) = vec3(0.5, 1.0, 0.5);  // Both: green
                    } else {
                        boneColor_$(n) = vec3(params.$(n)ColorMask.r, params.$(n)ColorMask.g, params.$(n)ColorMask.b);
                    }
                    baseColor = mix(baseColor, boneColor_$(n), labelAlpha_$(n));
                }
            """
            else
                code *= """
                if (params.$(n)isVisible == 1 && $(n)Res > 0.1) {
                    float labelAlpha_$(n) = clamp(params.$(n)maskContribution, 0.0, 1.0);
                    vec3 labelColor_$(n) = vec3(params.$(n)ColorMask.r, params.$(n)ColorMask.g, params.$(n)ColorMask.b);
                    baseColor = mix(baseColor, labelColor_$(n), labelAlpha_$(n));
                }
            """
            end
        end
    end

    return code
end

function _generate_multicolor_funcs(cont_specs)
    join(map(cont_specs) do spec
        colors = spec.colorSet
        N = length(colors)
        N == 0 && return ""
        n = spec.name
        entries = join(["vec3($(Float32(c.r)), $(Float32(c.g)), $(Float32(c.b)))" for c in colors], ",\n        ")
        """
        const vec3 $(n)ContColorTable[$(N + 1)] = vec3[$(N + 1)](
            vec3(0.0),
            $entries
        );

        vec3 getMultiColor_$(n)(float innertexelRes) {
            float texelRes = clamp(innertexelRes, params.$(n)minValue, params.$(n)maxValue);
            float normalized = ((texelRes - params.$(n)minValue) / max(float(params.$(n)ValueRange), 0.001)) * float($(N + 1));
            uint indexx = uint(floor(normalized));
            float normalizedColorPercent = normalized - float(indexx);
            uint prevIdx = uint(clamp(int(indexx) - 1, 0, $N));
            uint curIdx = clamp(indexx, 0u, uint($N));
            return clamp($(n)ContColorTable[curIdx] * normalizedColorPercent + $(n)ContColorTable[prevIdx] * (1.0 - normalizedColorPercent), 0.0, 1.0);
        }
        """
    end, "\n")
end

function _generate_discrete_color_funcs(discrete_specs)
    join(map(discrete_specs) do spec
        colors = spec.colorSet
        N = length(colors)
        N == 0 && return ""
        n = spec.name
        entries = join(["vec3($(Float32(c.r)), $(Float32(c.g)), $(Float32(c.b)))" for c in colors], ",\n        ")
        """
        const vec3 $(n)DiscreteColorTable[$(N + 1)] = vec3[$(N + 1)](
            vec3(0.0),
            $entries
        );

        vec3 getDiscreteColor_$(n)(float innertexelRes) {
            uint val = uint(round(innertexelRes));
            if (val == 0u) {
                return vec3(0.0);
            }
            uint indexx = ((val - 1u) % uint($N)) + 1u;
            return $(n)DiscreteColorTable[indexx];
        }
        """
    end, "\n")
end

end # module VulkanShaders
