; =====================================================================
; Inno Setup 6 Script for MedEye3D Standalone Windows Installer
; =====================================================================

#define MyAppName "MedEye3D"
#define MyAppVersion "0.5.8"
#define MyAppPublisher "JuliaHealth / Dr. Jakub Mitura"
#define MyAppURL "https://github.com/JuliaHealth/MedEye3d.jl"
#define MyAppExeName "MedEye3D.exe"
#define MyAppAppId "{{48A1AF7B-3279-4EEB-8F2B-7CA229BB51B1}}"

[Setup]
; Unique App ID (derived from MedEye3d Project.toml UUID)
AppId={#MyAppAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} v{#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

; Destination directories
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes

; Output settings
OutputDir=..\..\dist
OutputBaseFilename=MedEye3D_v{#MyAppVersion}_Setup
SetupIconFile=app_icon.ico
UninstallDisplayIcon={app}\bin\{#MyAppExeName}

; Compression & Optimization
Compression=lzma2/max
SolidCompression=yes
LZMAUseSeparateProcess=yes
LZMANumBlockThreads=4

; Modern UI Style & 64-bit Requirement
WizardStyle=modern
WizardSizePercent=100
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes

; Privileges required for Program Files and System Associations
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "fileassoc_nii"; Description: "Associate MedEye3D with NIfTI images (.nii, .nii.gz)"; GroupDescription: "File Associations:"
Name: "fileassoc_mha"; Description: "Associate MedEye3D with MetaImage files (.mha, .mhd)"; GroupDescription: "File Associations:"; Flags: unchecked
Name: "fileassoc_h5"; Description: "Associate MedEye3D with HDF5 Medical files (.h5, .hdf5)"; GroupDescription: "File Associations:"; Flags: unchecked

[Files]
; Distribute all files generated by PackageCompiler.create_app()
Source: "..\..\build\MedEye3D_dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "app_icon.ico"; DestDir: "{app}\bin"; Flags: ignoreversion

[Icons]
; Start Menu shortcuts
Name: "{autoprograms}\{#MyAppName}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"; IconFilename: "{app}\bin\app_icon.ico"
Name: "{autoprograms}\{#MyAppName}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"

; Optional Desktop shortcut
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"; IconFilename: "{app}\bin\app_icon.ico"; Tasks: desktopicon

[Registry]
; NIfTI associations (.nii)
Root: HKA; Subkey: "Software\Classes\.nii"; ValueType: string; ValueName: ""; ValueData: "MedEye3D.NIfTI"; Flags: uninsdeletevalue; Tasks: fileassoc_nii
Root: HKA; Subkey: "Software\Classes\.nii\OpenWithProgids"; ValueType: string; ValueName: "MedEye3D.NIfTI"; ValueData: ""; Flags: uninsdeletevalue; Tasks: fileassoc_nii
Root: HKA; Subkey: "Software\Classes\MedEye3D.NIfTI"; ValueType: string; ValueName: ""; ValueData: "NIfTI Medical Image"; Flags: uninsdeletekey; Tasks: fileassoc_nii
Root: HKA; Subkey: "Software\Classes\MedEye3D.NIfTI\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\bin\{#MyAppExeName},0"; Tasks: fileassoc_nii
Root: HKA; Subkey: "Software\Classes\MedEye3D.NIfTI\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\bin\{#MyAppExeName}"" ""%1"""; Tasks: fileassoc_nii

; MetaImage associations (.mha)
Root: HKA; Subkey: "Software\Classes\.mha"; ValueType: string; ValueName: ""; ValueData: "MedEye3D.MetaImage"; Flags: uninsdeletevalue; Tasks: fileassoc_mha
Root: HKA; Subkey: "Software\Classes\MedEye3D.MetaImage"; ValueType: string; ValueName: ""; ValueData: "MetaImage 3D Medical Volume"; Flags: uninsdeletekey; Tasks: fileassoc_mha
Root: HKA; Subkey: "Software\Classes\MedEye3D.MetaImage\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\bin\{#MyAppExeName},0"; Tasks: fileassoc_mha
Root: HKA; Subkey: "Software\Classes\MedEye3D.MetaImage\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\bin\{#MyAppExeName}"" ""%1"""; Tasks: fileassoc_mha

; HDF5 associations (.h5)
Root: HKA; Subkey: "Software\Classes\.h5"; ValueType: string; ValueName: ""; ValueData: "MedEye3D.HDF5"; Flags: uninsdeletevalue; Tasks: fileassoc_h5
Root: HKA; Subkey: "Software\Classes\MedEye3D.HDF5"; ValueType: string; ValueName: ""; ValueData: "HDF5 Medical Dataset"; Flags: uninsdeletekey; Tasks: fileassoc_h5
Root: HKA; Subkey: "Software\Classes\MedEye3D.HDF5\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\bin\{#MyAppExeName},0"; Tasks: fileassoc_h5
Root: HKA; Subkey: "Software\Classes\MedEye3D.HDF5\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\bin\{#MyAppExeName}"" ""%1"""; Tasks: fileassoc_h5

[Run]
Filename: "{app}\bin\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
