"""
CustomFragShad stub — OpenGL GLSL 330 fragment shader generation removed.
Vulkan fragment shaders are generated by VulkanShaders.generate_vulkan_fragment_shader().
"""
module CustomFragShad
using ColorTypes
using ..ForDisplayStructs

export createShaderPartOfTexture

function createShaderPartOfTexture(textSpec, color)
    return ""  # Not used by Vulkan backend
end

end # module CustomFragShad
