content = read("src/display/LesionMetadataWindow.jl", String)

old1 = "if w.i_selected[] != idx\n                        w.i_selected[] = idx\n                    end\n                    w.selection[] = val_str"

new1 = "if w.i_selected[] != idx\n                        w.i_selected[] = idx\n                    end\n                    if w.selection[] != val_str\n                        w.selection[] = val_str\n                    end\n                    notify(w.selection)"
content = replace(content, old1 => new1)

old2 = "if haskey(field_widgets, \"Anatomic Location\") && field_widgets[\"Anatomic Location\"] isa Menu\n                                        opts = field_widgets[\"Anatomic Location\"].options[]\n                                        if !(loc in opts)\n                                            field_widgets[\"Anatomic Location\"].options[] = vcat(opts, [loc])\n                                        end\n                                        field_widgets[\"Anatomic Location\"].selection[] = loc\n                                    end\n                                    if !isempty(subloc) && haskey(field_widgets, \"Anatomical Sublocation\") && field_widgets[\"Anatomical Sublocation\"] isa Menu\n                                        opts = field_widgets[\"Anatomical Sublocation\"].options[]\n                                        if !(subloc in opts)\n                                            field_widgets[\"Anatomical Sublocation\"].options[] = vcat(opts, [subloc])\n                                        end\n                                        field_widgets[\"Anatomical Sublocation\"].selection[] = subloc\n                                    end"

new2 = "if haskey(field_widgets, \"Anatomic Location\") && field_widgets[\"Anatomic Location\"] isa Menu\n                                        opts = field_widgets[\"Anatomic Location\"].options[]\n                                        idx = findfirst(==(loc), opts)\n                                        if idx === nothing\n                                            opts = vcat(opts, [loc])\n                                            field_widgets[\"Anatomic Location\"].options[] = opts\n                                            idx = length(opts)\n                                        end\n                                        _set_menu_idx!(field_widgets[\"Anatomic Location\"], idx)\n                                        if field_widgets[\"Anatomic Location\"].selection[] != loc\n                                            field_widgets[\"Anatomic Location\"].selection[] = loc\n                                        end\n                                    end\n                                    if !isempty(subloc) && haskey(field_widgets, \"Anatomical Sublocation\") && field_widgets[\"Anatomical Sublocation\"] isa Menu\n                                        opts = field_widgets[\"Anatomical Sublocation\"].options[]\n                                        idx = findfirst(==(subloc), opts)\n                                        if idx === nothing\n                                            opts = vcat(opts, [subloc])\n                                            field_widgets[\"Anatomical Sublocation\"].options[] = opts\n                                            idx = length(opts)\n                                        end\n                                        _set_menu_idx!(field_widgets[\"Anatomical Sublocation\"], idx)\n                                        if field_widgets[\"Anatomical Sublocation\"].selection[] != subloc\n                                            field_widgets[\"Anatomical Sublocation\"].selection[] = subloc\n                                        end\n                                    end"
content = replace(content, old2 => new2)

write("src/display/LesionMetadataWindow.jl", content)
