content = read("src/display/LesionMetadataWindow.jl", String)

# Patch 1: Makie Menu prefill for existing lesions
content = replace(content, r"if w\.i_selected\[\] != idx\s+w\.i_selected\[\] = idx\s+end\s+w\.selection\[\] = val_str"m => "if w.i_selected[] != idx\n                        w.i_selected[] = idx\n                    end\n                    if w.selection[] != val_str\n                        w.selection[] = val_str\n                    end\n                    notify(w.selection)")

# Patch 2: Makie Menu prefill for new lesions
content = replace(content, r"if haskey\(field_widgets, \"Anatomic Location\"\).*?field_widgets\[\"Anatomical Sublocation\"\].selection\[\] = subloc\s+end"s => "if haskey(field_widgets, \"Anatomic Location\") && field_widgets[\"Anatomic Location\"] isa Menu\n                                        opts = field_widgets[\"Anatomic Location\"].options[]\n                                        idx = findfirst(==(loc), opts)\n                                        if idx === nothing\n                                            opts = vcat(opts, [loc])\n                                            field_widgets[\"Anatomic Location\"].options[] = opts\n                                            idx = length(opts)\n                                        end\n                                        _set_menu_idx!(field_widgets[\"Anatomic Location\"], idx)\n                                        if field_widgets[\"Anatomic Location\"].selection[] != loc\n                                            field_widgets[\"Anatomic Location\"].selection[] = loc\n                                        end\n                                    end\n                                    if !isempty(subloc) && haskey(field_widgets, \"Anatomical Sublocation\") && field_widgets[\"Anatomical Sublocation\"] isa Menu\n                                        opts = field_widgets[\"Anatomical Sublocation\"].options[]\n                                        idx = findfirst(==(subloc), opts)\n                                        if idx === nothing\n                                            opts = vcat(opts, [subloc])\n                                            field_widgets[\"Anatomical Sublocation\"].options[] = opts\n                                            idx = length(opts)\n                                        end\n                                        _set_menu_idx!(field_widgets[\"Anatomical Sublocation\"], idx)\n                                        if field_widgets[\"Anatomical Sublocation\"].selection[] != subloc\n                                            field_widgets[\"Anatomical Sublocation\"].selection[] = subloc\n                                        end\n                                    end")

write("src/display/LesionMetadataWindow.jl", content)
