name: Documenter

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  statuses: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      
      - name: Load Julia packages from cache
        id: julia-cache
        uses: julia-actions/cache@v2
      
      - name: Build and deploy docs
        uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          GKSwstype: "100"
          JULIA_DEBUG: "Documenter"
          DATADEPS_ALWAYS_ACCEPT: true
      
      - name: Save Julia depot cache on cancel or failure
        id: julia-cache-save
        if: cancelled() || failure()
        uses: actions/cache/save@v4
        with: 
          path: |
            ${{ steps.julia-cache.outputs.cache-paths }}
          key: ${{ steps.julia-cache.outputs.cache-key }}